import { StyleSheet, Dimensions } from 'react-native';
export const styles = StyleSheet.create({
    fondo: {
        flex: 1,
        width: Dimensions.get('window').width,
        height: Dimensions.get('window').height,
    },
    scrollContainer: {
        paddingBottom: 500,
        paddingHorizontal: 10,
        flexGrow: 1,
    },
    vista1: {
        width: '100%',
        height: Dimensions.get('window').height - 100,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingTop: 100,
        flex: 1,
    },
    videoContainer: {
        width: '100%',
        marginTop: 20,
        marginBottom: 20,
        alignItems: 'center',
    },
    title: {
        textAlign: 'center',
        color: 'white',
        marginTop: 0,
        marginBottom: 20,
        fontSize: 27,
        fontWeight: 800,
    },

    imgSlide: {
        width: '100%',
        height: 300,
        objectFit: 'cover',
        marginTop: 30
    },
    title2: {
        fontSize: 24,
        color: 'white',
        marginTop: 15,
        marginBottom: 15,
        fontWeight: 800,
        textAlign: 'center',
    },
    description: {
        color: 'white',
        marginTop: 0,
        marginBottom: 20,
        fontSize: 17,
        fontWeight: 500,
        textAlign: 'center',
        backgroundColor: 'rgba(0,0,0,0.3)',
        borderRadius: 12,
        padding: 10,
        alignItems: 'center',
        borderColor: 'rgba(255,255,255,0.2)',
        borderWidth: 1,
    },
    boxBtn: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 70
    },
    btnExplore: {
        backgroundColor: '#0f0f0f',
        height: 60,
        paddingHorizontal: 30,
        borderRadius: 40,
        borderWidth: 2,
        borderColor: 'white',
        shadowColor: 'white',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 1,
        shadowRadius: 5,
        elevation: 10,
        alignItems: 'center',
        marginVertical: 10,
        flexDirection: 'row',
        gap: 10
    },
    txtExplore: {
        color: 'white',
        fontSize: 18,
        fontWeight: 'bold',
        textShadowColor: 'white',
        textShadowOffset: { width: 0, height: 0 },
        textShadowRadius: 10,
    },
    lottieAnimation: {
        width: 40,
        height: 40,
        transform: [{rotate: '35deg'}]
    },
    imgBtn:{
        width: 30,
        height: 30,
        tintColor: 'white',
        // marginBottom: 4,
    },

    // Estilos para NasaImageOfDay
    apodContainer: {
        backgroundColor: 'rgba(0,0,0,0.6)',
        borderRadius: 15,
        padding: 15,
        marginVertical: 30,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.3)',
    },
    apodTitle: {
        color: 'white',
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 15,
        textShadowColor: 'rgba(0,0,0,0.8)',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 3,
    },
    imageContainer: {
        position: 'relative',
        width: '100%',
        height: 200,
        marginBottom: 10,
        borderRadius: 10,
        overflow: 'hidden',
    },
    imageLoader: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.5)',
        zIndex: 1,
    },
    apodImage: {
        width: '100%',
        height: 200,
        borderRadius: 10,
    },
    apodExplanation: {
        color: 'white',
        fontSize: 14,
        lineHeight: 20,
        textAlign: 'justify',
        opacity: 0.9,
    },

    // Estilos para VisitorCounter
    counterContainer: {
        backgroundColor: 'rgba(255,255,255,0.1)',
        borderRadius: 25,
        paddingVertical: 15,
        paddingHorizontal: 25,
        marginVertical: 30,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
    },
    counterText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '600',
        textAlign: 'center',
        textShadowColor: 'rgba(0,0,0,0.8)',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 2,
    },

    // Estilos para AlienMessage
    alienContainer: {
        position: 'absolute',
        bottom: 80,
        width: '100%',
        height: 150,
    },
    ufoButton: {
        position: 'absolute',
        bottom: 20,
        right: 20,
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: 'rgba(0,0,0,0.7)',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.3)',
        shadowColor: '#fff',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.5,
        shadowRadius: 4,
        elevation: 5,
    },
    ufoIcon: {
        fontSize: 30,
    },
    messageBubble: {
        position: 'absolute',
        bottom: 90,
        right: 20,
        backgroundColor: 'rgba(0,0,0,0.9)',
        borderRadius: 15,
        padding: 12,
        maxWidth: 200,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.3)',
        shadowColor: '#fff',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 5,
    },
    messageText: {
        color: 'white',
        fontSize: 14,
        textAlign: 'center',
        fontWeight: '500',
    },
});
